version: '3.7'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=personal_finance_tracker_dev
      - JWT_SECRET=your_secret_key
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: personal_finance_tracker_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
